#pragma once
/*
 * DBI 791-ru UI byte-level layout tables.
 *
 * Derived from /opt/aimeld-proj/re/analysis/ui_screens_791.md
 * (FINDINGS.md Part 41).
 *
 * Strategy: each screen is a flat array of `ui_cell_t` records.
 * `ui_paint_layout()` walks the array and emits the same ANSI
 * byte stream DBI emits — no bitmap painter, no guesswork.
 *
 * Colors mirror the DBI palette recovered at 0x710069a080..0x710069d798:
 *   37;1 white bold (default)   31;1 red bold (errors)
 *   32;1 green bold             33;1 yellow bold
 *   36;1 cyan bold (titles)     38;2;R;G;B true-color
 * BG slots 40 (black, night/default) and 44;1 (blue, day).
 */

#include <stdint.h>
#include <stdbool.h>

typedef enum {
    UI_FG_DEFAULT = 0,   /* 37;1 white bold */
    UI_FG_WHITE   = 37,
    UI_FG_RED     = 31,
    UI_FG_GREEN   = 32,
    UI_FG_YELLOW  = 33,
    UI_FG_MAGENTA = 35,
    UI_FG_CYAN    = 36,
    UI_FG_BLACK   = 30,
    UI_FG_LIME_RGB    = 1001,   /* 38;2;50;205;50   */
    UI_FG_GREY_RGB    = 1002,   /* 38;2;220;220;220 */
    UI_FG_ORANGE_RGB  = 1003,   /* 38;2;255;128;0   */
} ui_fg_t;

typedef enum {
    UI_FLAG_BOLD     = 1 << 0,  /* SGR 1m */
    UI_FLAG_INVERT   = 1 << 1,  /* SGR 7m (selection bar) */
    UI_FLAG_PAD_ROW  = 1 << 2,  /* pad trailing spaces to UI_COLS-col */
    UI_FLAG_DIM      = 1 << 3,  /* SGR 37m (unbold white) */
} ui_flag_t;

/* One cell = one screen element at (row, col) with colored text. */
typedef struct {
    int         row;   /* 1-indexed, 1..45 */
    int         col;   /* 1-indexed, 1..80 */
    const char *text;  /* NULL => dynamic, filled by layout walker */
    int         fg;    /* ui_fg_t */
    int         flags; /* bitmask of ui_flag_t */
} ui_cell_t;

typedef struct {
    const char   *title;   /* screen title for top bar */
    const ui_cell_t *cells;
    int           n;
} ui_layout_t;

/* -- static layouts (from DBI 791-ru rodata) --------------------------- */

extern const ui_layout_t UI_LAYOUT_MAIN;
extern const ui_layout_t UI_LAYOUT_BROWSE_SD;
extern const ui_layout_t UI_LAYOUT_USB_HOST;
extern const ui_layout_t UI_LAYOUT_BROWSE_APPS;
extern const ui_layout_t UI_LAYOUT_TICKETS;
extern const ui_layout_t UI_LAYOUT_SAVES;
extern const ui_layout_t UI_LAYOUT_MTP;
extern const ui_layout_t UI_LAYOUT_FTP;
extern const ui_layout_t UI_LAYOUT_HTTP;
extern const ui_layout_t UI_LAYOUT_LOG;
extern const ui_layout_t UI_LAYOUT_SETTINGS;
extern const ui_layout_t UI_LAYOUT_INFO;
extern const ui_layout_t UI_LAYOUT_INSTALL;
extern const ui_layout_t UI_LAYOUT_TOOLS;
extern const ui_layout_t UI_LAYOUT_BROWSE_SYSTEM;
extern const ui_layout_t UI_LAYOUT_BROWSE_USER;
extern const ui_layout_t UI_LAYOUT_BACKEND_INSTALL;
extern const ui_layout_t UI_LAYOUT_GAMECARD;
extern const ui_layout_t UI_LAYOUT_NETWORK;
extern const ui_layout_t UI_LAYOUT_USBMS;

/* Main menu entries, in the order displayed by the 791-ru screenshot.
 * Each entry carries: the internal ID string (rodata xref, immutable)
 * plus the localized UX label shipped by the upstream 791-ru build.
 * NULL label => group spacer (non-selectable). */
typedef struct {
    int         screen_id;   /* maps to ui_screen_t in ui.h */
    const char *internal_id; /* rodata label, e.g. "BrowseSD" */
    const char *ux_label;    /* visible label, English */
} ui_menu_item_t;

extern const ui_menu_item_t UI_MAIN_MENU[];
extern const int            UI_MAIN_MENU_N;

/* MTP storage list (addresses 0x71006a05d0..0x71006a06b0 in rodata). */
extern const char *const UI_MTP_STORAGES[];
extern const int         UI_MTP_STORAGES_N;

/* -- walker ------------------------------------------------------------ */

/* Emit the exact ANSI+text byte stream of a layout to stdout. */
void ui_paint_layout(const ui_layout_t *layout);

/* Helper: push a dynamic row into a reusable layout scratch buffer. */
void ui_layout_row(int row, int col, const char *text, int fg, int flags);

/* -- trace-driven layouts (auto-generated from upstream paint traces) -- */

/* Defined in ui_traces_gen.c, generated by scripts/gen_ui_traces.py from
 * /opt/aimeld-proj/re/analysis/paint_trace_*_887.tsv.  Each layout is the
 * verbatim cell-by-cell capture of an upstream DBI screen at paint time.
 * Render pipeline is unchanged 887→891 (FINDINGS Part 45) so these
 * byte-match what upstream draws on 891 hardware. */
extern const ui_layout_t UI_TRACE_MAIN;
extern const ui_layout_t UI_TRACE_BROWSE_SD;
extern const ui_layout_t UI_TRACE_BROWSE_SYSTEM;
extern const ui_layout_t UI_TRACE_BROWSE_USER;
extern const ui_layout_t UI_TRACE_USB_HOST;
extern const ui_layout_t UI_TRACE_BACKEND_INSTALL;
extern const ui_layout_t UI_TRACE_GAMECARD;
extern const ui_layout_t UI_TRACE_NETWORK;
extern const ui_layout_t UI_TRACE_BROWSE_APPS;
extern const ui_layout_t UI_TRACE_TOOLS;
extern const ui_layout_t UI_TRACE_TICKETS;
extern const ui_layout_t UI_TRACE_SAVES;
extern const ui_layout_t UI_TRACE_MTP;
extern const ui_layout_t UI_TRACE_FTP;
extern const ui_layout_t UI_TRACE_HTTP;
extern const ui_layout_t UI_TRACE_LOG;
extern const ui_layout_t UI_TRACE_SETTINGS;
extern const ui_layout_t UI_TRACE_INFO;
extern const ui_layout_t UI_TRACE_INSTALL;

/* Walk a trace-derived layout and emit its cells exactly (no chrome,
 * no centered title — every cell is positioned absolutely from the
 * upstream paint trace). */
void ui_paint_trace(const ui_layout_t *layout);
