#!/usr/bin/env python3
"""Generate ui_traces_gen.c from /opt/aimeld-proj/re/analysis/paint_trace_*.tsv.

Each upstream paint trace is a cell-by-cell record (row, col, char, fg, bg,
bold, invert) of one DBI screen.  We coalesce consecutive cells in the same
row that share attributes into ui_cell_t records, mapping the (fg, bold,
invert) tuple to our UI_FG_* / UI_FLAG_* enum.

Output:
    ui_traces_gen.c  — auto-generated, do not edit by hand.
"""
import os
import sys
import csv
from glob import glob

TRACES = "/opt/aimeld-proj/re/analysis/paint_trace_{name}_887.tsv"

SCREENS = [
    ("MAIN",            "main"),
    ("BROWSE_SD",       "browse_sd"),
    ("BROWSE_SYSTEM",   "browse_system"),
    ("BROWSE_USER",     "browse_user"),
    ("USB_HOST",        "usb_host"),
    ("BACKEND_INSTALL", "backend_install"),
    ("GAMECARD",        "gamecard"),
    ("NETWORK",         "network"),
    ("BROWSE_APPS",     "browse_apps"),
    ("TOOLS",           "tools"),
    ("TICKETS",         "tickets"),
    ("SAVES",           "saves"),
    ("MTP",             "mtp"),
    ("FTP",             "ftp"),
    ("HTTP",            "http"),
    ("LOG",             "log"),
    ("SETTINGS",        "settings"),
    ("INFO",            "info"),
    ("INSTALL",         "install"),
]


def attr_to_flags(fg, bold, invert):
    """Map (fg, bold, invert) → (UI_FG_*, UI_FLAG_* bitmask)."""
    if fg == 36:
        ui_fg = "UI_FG_CYAN"
    else:
        ui_fg = "UI_FG_WHITE"

    flags = []
    if bold:
        flags.append("UI_FLAG_BOLD")
    else:
        flags.append("UI_FLAG_DIM")
    if invert:
        flags.append("UI_FLAG_INVERT")

    return ui_fg, " | ".join(flags) if flags else "0"


def coalesce_row(cells):
    """Coalesce same-row cells that are contiguous and share attributes."""
    cells = sorted(cells, key=lambda c: c["col"])
    runs = []
    cur = None
    for c in cells:
        key = (c["fg"], c["bold"], c["invert"])
        if cur is None:
            cur = {"col": c["col"], "text": c["text"], "key": key}
        elif (
            cur["key"] == key
            and c["col"] == cur["col"] + sum(1 for _ in cur["text"])
        ):
            cur["text"] += c["text"]
        else:
            runs.append(cur)
            cur = {"col": c["col"], "text": c["text"], "key": key}
    if cur is not None:
        runs.append(cur)
    return runs


def emit_screen(name, fname, out):
    path = TRACES.format(name=fname)
    if not os.path.exists(path):
        print(f"  [SKIP] {fname} — no trace TSV", file=sys.stderr)
        return False

    # Trace records every paint op in order; the FINAL visible char at (row,col)
    # is the LAST write. Dedup keyed by (row,col), keeping the last entry.
    last_at = {}
    with open(path) as f:
        rd = csv.DictReader(f, delimiter="\t")
        for r in rd:
            key = (int(r["row"]), int(r["col"]))
            last_at[key] = {
                "col":    int(r["col"]),
                "text":   r["text"],
                "fg":     int(r["fg"]),
                "bold":   int(r["bold"]),
                "invert": int(r["invert"]),
            }
    rows = {}
    for (row, _col), c in last_at.items():
        rows.setdefault(row, []).append(c)

    out.write(f"\n/* ---- {name} (from paint_trace_{fname}_887.tsv) ----- */\n")
    out.write(f"static const ui_cell_t TRACE_{name}_CELLS[] = {{\n")
    n = 0
    for row in sorted(rows):
        runs = coalesce_row(rows[row])
        for run in runs:
            ui_fg, flags = attr_to_flags(*run["key"])
            text = run["text"].replace("\\", "\\\\").replace('"', '\\"')
            out.write(
                f'    {{ {row:>2}, {run["col"]:>2}, "{text}", {ui_fg}, {flags} }},\n'
            )
            n += 1
    out.write("};\n")
    out.write(
        f"const ui_layout_t UI_TRACE_{name} = "
        f'{{ "{name}", TRACE_{name}_CELLS, '
        f"(int)(sizeof TRACE_{name}_CELLS / sizeof TRACE_{name}_CELLS[0]) }};\n"
    )
    print(f"  [OK]   {fname:<18} {n:>4} cells")
    return True


def main():
    out_path = "/opt/aimeld-proj/dbi-fork-git/fork/source/ui_traces_gen.c"
    with open(out_path, "w") as out:
        out.write(
            "/* AUTO-GENERATED by scripts/gen_ui_traces.py — do not edit.\n"
            " *\n"
            " * Source of truth: /opt/aimeld-proj/re/analysis/paint_trace_*_887.tsv\n"
            " * Per Part 45 of FINDINGS.md the render pipeline is unchanged 887→891.\n"
            " */\n"
            "#include \"ui_layouts.h\"\n"
        )
        for name, fname in SCREENS:
            emit_screen(name, fname, out)

    print(f"\nWritten: {out_path}")


if __name__ == "__main__":
    main()
